[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24" # Match your Solidity version here
remappings = ["forge-std=forge-std","forge-std=lib/forge-std","@openzeppelin-contracts/=lib/openzeppelin-contracts/","@openzeppelin/=lib/openzeppelin-contracts/","solmate/=lib/solmate","erc1363/=lib/erc1363-payable-token"]
#sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'         # the address of `msg.sender` in tests
#tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'      # the address of `tx.origin` in tests


[etherscan]
#mainnet = { key = "${ETHERSCAN_API_KEY}" }
#sepolia = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
 #sepolia = "https://sepolia.infura.io/v3/${API_KEY_INFURA}"
 anvil = "http://127.0.0.1:8545"
